ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "idempotencyKey" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "accountTotalCharges" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "totalPaidToDate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "totalDueNow" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "newChargesTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "previousOutstanding" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "termId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "scheduledFor" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "smsMessageId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "smsStatus" TEXT DEFAULT 'pending';

DROP INDEX IF EXISTS "Invoice_idempotencyKey_key";
CREATE UNIQUE INDEX "Invoice_idempotencyKey_key" ON "Invoice"("idempotencyKey");

CREATE INDEX IF NOT EXISTS "Invoice_userId_termId_idx" ON "Invoice"("userId", "termId");
CREATE INDEX IF NOT EXISTS "Invoice_smsMessageId_idx" ON "Invoice"("smsMessageId");
